bootctrl: Have libboot_control_qti depend on libgptutils.qcom
 * hardware/qcom-caf/bootctrl/1.1/libboot_control_qti/
   libboot_control_qti.cpp:50:10: fatal error: 'gpt-utils.h' file not found

Change-Id: I5dfa5c7311644e688e959e35e38fd61de1cd823d